source 'http://rubygems.org'

gem 'rails', '3.0.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', '1.2.5', :require => 'sqlite3'
gem 'rspec-rails', '>= 2.0.0.beta.19', :group => :test
gem 'rubycas-client', '2.2.1', :require => 'casclient'
gem 'state_machine', '0.9.3'
gem 'json', '1.1.3'
gem 'formtastic', '1.1.0'
gem 'inherited_resources', '1.1.2'

# use thin instead of webrick for development
gem 'thin'

# To use debugger
gem 'ruby-debug'
